common:
#RS LiDar
    lid_topic: "/ouster/points"
    imu_topic: "/ouster/imu"
#    imu_topic: "yesense_imu/imu/data"
    gnss_topic: "rtk_pos_raw"
    leg_topic: "/leg_odom"
    # lid_topic: "/rslidar_points1"
    # imu_topic: "/imu/data1"
    time_sync_en: false       # ONLY turn on when external time synchronization is really not possible

    pub_firstodo_en: false    #是否发布初始变换
    
preprocess:
    lidar_type: 3                # 1 for Livox serials LiDAR, 2 for Velodyne LiDAR, 3 for ouster LiDAR, 4 RS
    scan_line: 32
    scan_rate: 10                # only need to be set for velodyne, unit: Hz,
    timestamp_unit: 3                 # 0-second, 1-milisecond, 2-microsecond, 3-nanosecond.
    blind: 0.8

mapping:
    acc_cov: 0.1
    gyr_cov: 0.1
    b_acc_cov: 0.0001
    b_gyr_cov: 0.0001
    fov_degree:    180
    det_range:     40
    extrinsic_est_en:  false      # true: enable the online estimation of IMU-LiDAR extrinsic,
    #extrinsic_T: [ 0, 0, 0]
    #extrinsic_R: [ 1, 0, 0,
    #               0, 1, 0,
    #               0, 0, 1]
    extrinsic_T: [ 0, 0, 0] # 0 0 0
    extrinsic_R: [ 1.00000000001, 0, 0,
                  0, 1, 0,
                  0, 0, 1]
    rtk2Lidar_T: [-0.464, 0.200, 0.2045]

publish:
    path_en:  true
    scan_publish_en:  true       # false: close all the point cloud output
    dense_publish_en: true       # false: low down the points number in a global-frame point clouds scan.
    scan_bodyframe_pub_en: true  # true: output the point cloud scans in IMU-body-frame

surroundingkeyframeAddingDistThreshold: 1.0
surroundingkeyframeAddingAngleThreshold: 0.2

globalMapVisualizationSearchRadius: 50.0
globalMapVisualizationPoseDensity: 2.0
globalMapVisualizationLeafSize: 0.4

# GPS Settings
usertk: true
gpsCovThreshold: 0.2
poseCovThreshold: 0.01
useGpsElevation: true
status_threshold: 1
Search_Radius: 10.0 #室内查找半径
Search_Radius_rtk: 30.0 #RTK室外查找半径

useleg: false
Reposition_type: 2 #1 for rtk ,2 for manual

numberOfCores: 2
recontructKdTree: true
#loadmappath: "/home/syx/111/na_localization_lslidar_0/src/na_localization/PCD/twofloor/cloud_map.pcd"
#loadposepath: "/home/syx/111/na_localization_lslidar_0/src/na_localization/PCD/twofloor/pose.txt"
#params_filename: "/home/syx/111/na_localization_lslidar_0/src/na_localization/PCD/param.json"
loadmappath: "/home/syx/111/na_localization_lslidar_01/src/na_localization/PCD/cloud_map.pcd"
loadposepath: "/home/syx/111/na_localization_lslidar_01/src/na_localization/PCD/pose.txt"
params_filename: "/home/syx/111/na_localization_lslidar_01/src/na_localization/PCD/param.json"
